upstream auth_service {
    server auth-service:8001;
}

upstream task_service {
    server task-service:8002;
}

server {
    listen 80;
    server_name localhost;

    # =========================
    # AUTH SERVICE
    # =========================

    location /auth/ {
        proxy_pass http://auth_service/;

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header Authorization $http_authorization;

        # Correlation ID support
        proxy_set_header X-Correlation-ID $http_x_correlation_id;
    }

    # =========================
    # AUTH HEALTH
    # =========================

    location /auth/health {
        proxy_pass http://auth_service/health;

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }

    # =========================
    # TASK SERVICE
    # =========================

    location /tasks {
        proxy_pass http://task_service/tasks;

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header Authorization $http_authorization;

        proxy_set_header Content-Type $http_content_type;

        # Correlation ID support
        proxy_set_header X-Correlation-ID $http_x_correlation_id;
    }

    # =========================
    # TASK HEALTH
    # =========================

    location /tasks/health {
        proxy_pass http://task_service/health;

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }

    # =========================
    # TASK METRICS
    # =========================

    location /tasks/metrics {
        proxy_pass http://task_service/metrics;

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }

    # =========================
    # GATEWAY HEALTH
    # =========================

    location /health {
        default_type application/json;

        return 200
        '{"status":"healthy","service":"gateway"}';
    }

    # =========================
    # FRONTEND
    # =========================

    location / {
        proxy_pass http://frontend:80;

        proxy_set_header Host $host;

        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
    }
}