name: CD Pipeline

on:
  workflow_run:
    workflows: ["CI Pipeline"]
    types: [completed]
    branches: [main]

jobs:
  build-docker:
    name: 🐳 Build Docker
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    timeout-minutes: 10
    steps:
      - name: 📥 Checkout code
        uses: actions/checkout@v4
      - name: 🐳 Build Kelarin Backend Image
        run: docker build -t kelarin-backend:ci ./backend
      - name: 🐳 Build Kelarin Frontend Image
        run: docker build -t kelarin-frontend:ci ./frontend
